# =====================================================
# CAMPUSMIND AI - VOICE ASSISTANT ROUTES
# ElevenLabs Text-to-Speech with Real-time Lip-Sync Alignment
# =====================================================

import re
import requests
from flask import Blueprint, jsonify, request
from config.config import Config

voice_assistant_routes = Blueprint("voice_assistant_routes", __name__, url_prefix="/api/voice-assistant")


def clean_text_for_speech(raw_text: str, max_chars: int = 500) -> str:
    """
    Cleans markdown formatting, citations, code blocks, and symbols
    so that ElevenLabs speaks cleanly and expressively, while
    respecting free-tier character usage limits.
    """
    if not raw_text:
        return ""

    text = raw_text

    # Remove code blocks
    text = re.sub(r"```[\s\S]*?```", "", text)
    # Remove inline code
    text = re.sub(r"`[^`]+`", "", text)
    # Remove markdown links [text](url) -> text
    text = re.sub(r"\[([^\]]+)\]\([^\)]+\)", r"\1", text)
    # Remove markdown headers and bold/italic markers
    text = re.sub(r"[#*_~]", "", text)
    # Remove HTML tags
    text = re.sub(r"<[^>]+>", "", text)
    # Remove multiple spaces/newlines
    text = re.sub(r"\s+", " ", text).strip()

    # Free-tier quota protection: trim intelligently at sentence boundary
    if len(text) > max_chars:
        # Find last sentence end before max_chars
        boundary = text[:max_chars].rfind(".")
        if boundary > 100:
            text = text[:boundary + 1]
        else:
            text = text[:max_chars].rsplit(" ", 1)[0] + "..."

    return text


@voice_assistant_routes.route("/status", methods=["GET"])
def assistant_status():
    """
    Returns the operational status of the ElevenLabs voice assistant configuration.
    """
    api_key = (Config.ELEVENLABS_API_KEY or "").strip()
    return jsonify({
        "success": True,
        "configured": bool(api_key),
        "voice_id": Config.ELEVENLABS_VOICE_ID,
        "model_id": Config.ELEVENLABS_MODEL_ID,
        "features": {
            "avatar": "Ready Player Me 3D Avatar",
            "renderer": "TalkingHead.js + Three.js",
            "tts": "ElevenLabs with Timestamps",
            "wake_word": "Hey Campus"
        }
    })


@voice_assistant_routes.route("/speak", methods=["POST"])
def assistant_speak():
    """
    Accepts text generated by OpenRouter / Nemotron LLM,
    calls ElevenLabs TTS with word/character timestamps,
    and returns base64 audio + alignment viseme timing for TalkingHead.js.
    """
    api_key = (Config.ELEVENLABS_API_KEY or "").strip()
    if not api_key:
        return jsonify({
            "success": False,
            "error": "ELEVENLABS_API_KEY is not configured.",
            "instructions": "Please add your ElevenLabs API key to bakend/.env as ELEVENLABS_API_KEY=your_key."
        }), 400

    data = request.get_json(silent=True) or {}
    input_text = data.get("text", "")
    if not input_text or not input_text.strip():
        return jsonify({
            "success": False,
            "error": "Missing 'text' parameter in request body."
        }), 400

    # Clean text to optimize for natural vocal delivery & conserve character quota
    spoken_text = clean_text_for_speech(input_text)
    if not spoken_text:
        return jsonify({
            "success": False,
            "error": "Provided text contained no speakable words after stripping code and formatting."
        }), 400

    # ✅ UPDATED: "Rachel" voice (clear & professional female voice)
    voice_id = data.get("voice_id") or Config.ELEVENLABS_VOICE_ID or "21m00Tcm4TlvDq8ikWAM"
    model_id = data.get("model_id") or Config.ELEVENLABS_MODEL_ID or "eleven_flash_v2_5"

    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}/with-timestamps"
    headers = {
        "xi-api-key": api_key,
        "Content-Type": "application/json",
        "Accept": "application/json"
    }
    
    # ✅ UPDATED: Voice Settings for better clarity and stability
    payload = {
        "text": spoken_text,
        "model_id": model_id,
        "voice_settings": {
            "stability": 0.75,        # Increased for clearer voice
            "similarity_boost": 0.85, # Increased for more natural tone
            "style": 0.0,             # Keep neutral tone
            "use_speaker_boost": True # Boost clarity
        }
    }

    try:
        response = requests.post(url, json=payload, headers=headers, timeout=25)

        if response.status_code != 200:
            err_msg = f"ElevenLabs API error (HTTP {response.status_code})"
            try:
                err_detail = response.json().get("detail", response.text)
                err_msg = f"{err_msg}: {err_detail}"
            except Exception:
                err_msg = f"{err_msg}: {response.text}"
            return jsonify({
                "success": False,
                "error": err_msg
            }), response.status_code

        res_json = response.json()
        audio_b64 = res_json.get("audio_base64")
        alignment = res_json.get("alignment")

        if not audio_b64:
            return jsonify({
                "success": False,
                "error": "ElevenLabs returned 200 OK but audio_base64 was empty."
            }), 502

        return jsonify({
            "success": True,
            "audio_base64": audio_b64,
            "alignment": alignment,
            "spoken_text": spoken_text,
            "voice_id": voice_id,
            "model_id": model_id
        })

    except requests.exceptions.Timeout:
        return jsonify({
            "success": False,
            "error": "ElevenLabs API request timed out (25s)."
        }), 504
    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"Failed to synthesize speech: {str(e)}"
        }), 500